=== GuillermoJS95/Lenguajes2025-Guillermo-Jorge-Segura/SegundoTrimestre_Jorge_Segura_Guillermo/XML/ejercicios_xml/menu_restaurante/menu_restaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plato" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>

                            <xs:element name="primero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="gazpacho andaluz"/>
                                        <xs:enumeration value="ensalada de burrata"/>
                                        <xs:enumeration value="sopa de picadillo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="segundo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="xs:string"/>
                                        <xs:enumeration value="merluza a la plancha"/>
                                        <xs:enumeration value="entrecot de ternera"/>
                                        <xs:enumeration value="lasaña vegetal"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GuillermoJS95/Lenguajes2025-Guillermo-Jorge-Segura/SegundoTrimestre_Jorge_Segura_Guillermo/XML/ejercicios_xml/menu_restaurante/menu_restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="menu_restaurante.xsd">
    <plato>
        <nombre>Menú del Día</nombre>
        <precio>11.90</precio>
        <primero>gazpacho andaluz</primero>
        <segundo>merluza a la plancha</segundo>    
    </plato>

    <plato>
        <nombre>Combinado Gourmet</nombre>
        <precio>18.50</precio>
        <primero>ensalada de burrata</primero>
        <segundo>entrecot de ternera</segundo>
    </plato>
</menu>
